# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: paises_db
  pool: 5
  username: postgres
  password: sismat
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: paises_db
  pool: 5
  username: postgres
  password: sismat
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: paises_db
  pool: 5
  username: postgres
  password: sismat
  host: localhost