Country.delete_all

Country.create!(nome: 'Afeganistão', local: 'Ásia', capital: 'Kabul', extensao: 652230, idioma: 'Patcho,Dari', populacao: 33397058, pib: 19470000000, moeda: 'Afegane', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Afeganistão.gif"))
# Country.create!(nome: 'África do Sul', local: 'África', capital: 'Pretoria', extensao: 1219090, idioma: 'Aficaner e Inglês', populacao: 50738255, pib: 294840000000, moeda: 'Rand', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
Country.create!(nome: 'Albânia', local: 'Europa', capital: 'Tirana', extensao: 28750, idioma: 'Albanês', populacao: 3227373, pib: 13000000, moeda: 'Lek', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Albânia.gif"))
Country.create!(nome: 'Alemanha', local: 'Europa', capital: 'Berlim', extensao: 357120, idioma: 'Alemão', populacao: 83100000, pib: 3466760000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Alemanha.gif"))
Country.create!(nome: 'Andorra', local: 'Europa', capital: 'Andorra', extensao: 470, idioma: 'Catalão', populacao: 80000, pib: 3280000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Andorra.gif"))
Country.create!(nome: 'Angola', local: 'África', capital: 'Luanda', extensao: 1246700, idioma: 'Português', populacao: 21900000, pib: 89630000000, moeda: 'Kuanza', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Angola.gif"))
Country.create!(nome: 'Antigua e Barbuda', local: 'América Central', capital: 'Saint Johns', extensao: 440, idioma: 'Inglês', populacao: 92100, pib: 1450000000, moeda: 'Dólar do Caribe Oriental', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Antigua e Barbuda.gif"))
Country.create!(nome: 'Arábia Saudita', local: 'Ásia', capital: 'Riad', extensao: 2149690, idioma: 'Árabe', populacao: 30100000, pib: 646440000000, moeda: 'Rial', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Arábia Saudita.gif"))
Country.create!(nome: 'Argélia', local: 'África', capital: 'Argel', extensao: 2381740, idioma: 'Árabe', populacao: 36485828, pib: 156080000000, moeda: 'Dinar Argelino', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Argélia.gif"))
Country.create!(nome: 'Argentina', local: 'América do Sul', capital: 'Buenos Aires', extensao: 2791810, idioma: 'Espanhol', populacao: 41400000, pib: 545900000000, moeda: 'Peso Argentino', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Argentina.gif"))
Country.create!(nome: 'Armênia', local: 'Ásia', capital: 'Ierevan', extensao: 29740, idioma: 'Armênio', populacao: 29740, pib: 10550000000, moeda: 'Dram', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Armênia.gif"))
Country.create!(nome: 'Aruba', local: 'América do Sul', capital: 'Oranjestad', extensao: 193, idioma: 'Holandês', populacao: 104553, pib: 2580000000, moeda: 'Florim de Aruba', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Aruba.gif"))
Country.create!(nome: 'Austrália', local: 'Oceania', capital: 'Camberra', extensao: 7741220, idioma: 'Inglês', populacao: 24800000, pib: 1204620000000, moeda: 'Dólar Australiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Austrália.gif"))
Country.create!(nome: 'Áustria', local: 'Europa', capital: 'Viena', extensao: 83879, idioma: 'Alemão', populacao: 8710000, pib: 386430000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Áustria.gif"))
Country.create!(nome: 'Azerbaijão', local: 'Ásia', capital: 'Baku', extensao: 86600, idioma: 'Azerbaijano', populacao: 9680000, pib: 37850000000, moeda: 'Manat', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Azerbaijão.gif"))
Country.create!(nome: 'Bahamas', local: 'América Central', capital: 'Nassau', extensao: 13880, idioma: 'Inglês', populacao: 353500, pib: 9050000000, moeda: 'Dólar das Bahamas', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bahamas.gif"))
Country.create!(nome: 'Bangladesh', local: 'Ásia', capital: 'Dacca', extensao: 144000, idioma: 'Bengali', populacao: 154500000, pib: 221420000000, moeda: 'Taka', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bangladesh.gif"))
Country.create!(nome: 'Barbados', local: 'América Central', capital: 'Bridgetown', extensao: 430, idioma: 'Inglês', populacao: 275100, pib: 4590000000, moeda: 'Dólar de Barbados', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Barbados.gif"))
Country.create!(nome: 'Bahrein', local: 'Ásia', capital: 'Manama', extensao: 760, idioma: 'Árabe', populacao: 1608000, pib: 31860000000, moeda: 'Dinar de Bahrein', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bahrein.gif"))
Country.create!(nome: 'Belarus', local: 'Europa', capital: 'Minsk', extensao: 207600, idioma: 'Bielo-Russo,Russo', populacao: 10531000, pib: 47430000000, moeda: 'Rubio', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Belarus.gif"))
Country.create!(nome: 'Bélgica', local: 'Europa', capital: 'Bruxelas', extensao: 30530, idioma: 'Francês, Alemão, Holandês', populacao: 12310000, pib: 466370000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bélgica.gif"))

# Country.create!(nome: 'Belize', local: 'América Central', capital: 'Belmopan', extensao: 22970, idioma: 'Inglês', populacao: 378050, pib: 1770000000, moeda: 'Dólar de Belize', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Belize.gif"))

# Country.create!(nome: 'Benin', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 8580000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Bolívia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 33810000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Bósnia-Herzegóvina', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 16560000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Botsuana', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 15270000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Brasil', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 1796190000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Brunei', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 11400000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Bulgária', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 52400000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Burkina-Faso', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 12120000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Burundi', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 3010000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Butão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 2240000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Cabo Verde', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 1620000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Camarões', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 24200000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Camboja', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 18050000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Canadá', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 1529760000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Catar', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 152500000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Cazaquistão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 133660000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Chade', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 9600000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Chile', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 247000000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'China', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 11199150000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Chipre', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 19800000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Cingapura', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 296970000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Colômbia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 282460000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Comores', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 620000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Congo', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 35000000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Coréia do Norte', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 16120000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Coréia do Sul', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 1411250000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Costa do Marfim', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 36160000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Costa Rica', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 57440000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Croácia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 50430000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Cuba', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 87130000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Dinamarca', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 306140000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Djibuti', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 1730000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Dominica', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 530000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'Egito', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 26800000000, moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))

# Country.create!(nome: 'El Salvador', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Emirados Árabes', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Equador', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Eritréia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Eslováquia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Eslovênia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Espanha', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Estados Unidos', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Estônia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Etiópia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Fiji', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Filipinas', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Finlândia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'França', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Gabão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Gâmbia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Gana', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Geórgia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Granada', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Grécia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Guatemala', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Guiana', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Guiné', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Guiné Equatorial', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Guiné-Bissau', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Haiti', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Holanda', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Honduras', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Hong Kong', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Hungria', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Iêmen', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Ilha de Man', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Ilhas Cayman', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Ilhas Salomão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Índia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Indonésia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Irã', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Iraque', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Irlanda', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Islândia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Israel', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Itália', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Jamaica', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Japão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Jordânia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Kiribati', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Kosovo', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Kuwait', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Laos', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Lesoto', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Letônia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Líbano', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Libéria', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Líbia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Liechtenstein', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Lituânia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Luxemburgo', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Macau', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Macedônia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Madasgáscar', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Malásia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Malaui', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Maldivas', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Mali', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Malta', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Marrocos', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Maurício', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Mauritânia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'México', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Mianmar', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Micronésia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Moçambique', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Moldávia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Mônaco', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Mongólia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Montenegro', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Namíbia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Nepal', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Nicarágua', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Níger', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Nigéria', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Noruega', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Nova Zelândia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Omã', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Palau', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Palestina', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Panamá', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Papua Nova Guiné', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Paquistão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Paraguai', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Peru', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Polônia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Porto Rico', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Portugal', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Quênia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Quirguistão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Reino Unido', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'República Centro-Africana', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'República Democrática do Congo', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'República Dominicana', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'República Tcheca', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Romênia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Ruanda', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Rússia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Samoa', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'São Cristóvão e Neves', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'São Tomé e Príncipe', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'São Vicente e Granadinas', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Seychelles', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Senegal', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Serra Leoa', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Sérvia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Síria', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Somália', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Sri-Lanka', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Santa Lúcia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Suazilândia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Sudão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Sudão do Sul', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Suécia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Suíça', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Suriname', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Tadjiquistão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Tailândia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Taiwan', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Tanzânia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Timor Leste', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Togo', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Tonga', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Trinidad e Tobago', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Tunísia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Turcomenistão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Turquia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Ucrânia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Uganda', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Uruguai', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Uzbequistão', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Vanuatu', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Venezuela', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Vietnã', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Zâmbia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
# Country.create!(nome: 'Zimbábue', local: '', capital: '', extensao: , idioma: '', populacao: , pib: , moeda: '', ano_referencia: , :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/.gif"))
