Country.delete_all

Country.create!(nome: 'Afeganistão', local: 'Ásia', capital: 'Kabul', extensao: 652230, idioma: 'Patcho,Dari', populacao: 33397058, pib: 19470000000, moeda: 'Afegane', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Afeganistão.gif"))
Country.create!(nome: 'África do Sul', local: 'África', capital: 'Pretoria', extensao: 1219090, idioma: 'Aficaner e Inglês', populacao: 50738255, pib: 294840000000, moeda: 'Rand', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Africa_do_Sul.jpg"))
Country.create!(nome: 'Albânia', local: 'Europa', capital: 'Tirana', extensao: 28750, idioma: 'Albanês', populacao: 3227373, pib: 13000000, moeda: 'Lek', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Albânia.gif"))
Country.create!(nome: 'Alemanha', local: 'Europa', capital: 'Berlim', extensao: 357120, idioma: 'Alemão', populacao: 83100000, pib: 3466760000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Alemanha.gif"))
Country.create!(nome: 'Andorra', local: 'Europa', capital: 'Andorra', extensao: 470, idioma: 'Catalão', populacao: 80000, pib: 3280000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Andorra.jpg"))
Country.create!(nome: 'Angola', local: 'África', capital: 'Luanda', extensao: 1246700, idioma: 'Português', populacao: 21900000, pib: 89630000000, moeda: 'Kuanza', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Angola.jpg"))
Country.create!(nome: 'Antigua e Barbuda', local: 'América Central', capital: 'Saint Johns', extensao: 440, idioma: 'Inglês', populacao: 92100, pib: 1450000000, moeda: 'Dólar do Caribe Oriental', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Antigua e Barbuda.gif"))
Country.create!(nome: 'Arábia Saudita', local: 'Ásia', capital: 'Riad', extensao: 2149690, idioma: 'Árabe', populacao: 30100000, pib: 646440000000, moeda: 'Rial', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Arábia Saudita.gif"))
Country.create!(nome: 'Argélia', local: 'África', capital: 'Argel', extensao: 2381740, idioma: 'Árabe', populacao: 36485828, pib: 156080000000, moeda: 'Dinar Argelino', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Argélia.jpg"))
Country.create!(nome: 'Argentina', local: 'América do Sul', capital: 'Buenos Aires', extensao: 2791810, idioma: 'Espanhol', populacao: 41400000, pib: 545900000000, moeda: 'Peso Argentino', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Argentina.jpg"))
Country.create!(nome: 'Armênia', local: 'Ásia', capital: 'Ierevan', extensao: 29740, idioma: 'Armênio', populacao: 29740, pib: 10550000000, moeda: 'Dram', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Armênia.jpg"))
Country.create!(nome: 'Aruba', local: 'América do Sul', capital: 'Oranjestad', extensao: 193, idioma: 'Holandês', populacao: 104553, pib: 2580000000, moeda: 'Florim de Aruba', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Aruba.gif"))
Country.create!(nome: 'Austrália', local: 'Oceania', capital: 'Camberra', extensao: 7741220, idioma: 'Inglês', populacao: 24800000, pib: 1204620000000, moeda: 'Dólar Australiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Austrália.gif"))
Country.create!(nome: 'Áustria', local: 'Europa', capital: 'Viena', extensao: 83879, idioma: 'Alemão', populacao: 8710000, pib: 386430000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Áustria.gif"))
Country.create!(nome: 'Azerbaijão', local: 'Ásia', capital: 'Baku', extensao: 86600, idioma: 'Azerbaijano', populacao: 9680000, pib: 37850000000, moeda: 'Manat', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Azerbaijão.jpg"))
Country.create!(nome: 'Bahamas', local: 'América Central', capital: 'Nassau', extensao: 13880, idioma: 'Inglês', populacao: 353500, pib: 9050000000, moeda: 'Dólar das Bahamas', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bahamas.gif"))
Country.create!(nome: 'Bangladesh', local: 'Ásia', capital: 'Dacca', extensao: 144000, idioma: 'Bengali', populacao: 154500000, pib: 221420000000, moeda: 'Taka', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bangladesh.gif"))
Country.create!(nome: 'Barbados', local: 'América Central', capital: 'Bridgetown', extensao: 430, idioma: 'Inglês', populacao: 275100, pib: 4590000000, moeda: 'Dólar de Barbados', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Barbados.png"))
Country.create!(nome: 'Bahrein', local: 'Ásia', capital: 'Manama', extensao: 760, idioma: 'Árabe', populacao: 1608000, pib: 31860000000, moeda: 'Dinar de Bahrein', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bahrein.gif"))
Country.create!(nome: 'Belarus', local: 'Europa', capital: 'Minsk', extensao: 207600, idioma: 'Bielo-Russo,Russo', populacao: 10531000, pib: 47430000000, moeda: 'Rubio', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Belarus.gif"))
Country.create!(nome: 'Bélgica', local: 'Europa', capital: 'Bruxelas', extensao: 30530, idioma: 'Francês, Alemão, Holandês', populacao: 12310000, pib: 466370000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bélgica.gif"))
Country.create!(nome: 'Belize', local: 'América Central', capital: 'Belmopan', extensao: 22970, idioma: 'Inglês', populacao: 378050, pib: 1770000000, moeda: 'Dólar de Belize', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Belize.png"))
Country.create!(nome: 'Benin', local: 'África', capital: 'Porto Novo', extensao: 112620, idioma: 'Francês', populacao: 9850000, pib: 8580000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Benin.gif"))
Country.create!(nome: 'Bolívia', local: 'América do Sul', capital: 'La Paz', extensao: 1098580, idioma: 'Espanhol', populacao: 10718000, pib: 33810000000, moeda: 'Boliviano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bolívia.png"))
Country.create!(nome: 'Bósnia-Herzegóvina', local: 'Europa', capital: 'Saravejo', extensao: 51210, idioma: 'Bósnio', populacao: 4063070, pib: 16560000000, moeda: 'Marco Convertível', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bósnia-Herzegovina.png"))
Country.create!(nome: 'Botswana', local: 'África', capital: 'Gaborone', extensao: 581730, idioma: 'Inglês', populacao: 2279070, pib: 15270000000, moeda: 'Pula', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Botswana.png"))
Country.create!(nome: 'Brasil', local: 'América do Sul', capital: 'Brasília', extensao: 8515767, idioma: 'Português', populacao: 207009000, pib: 1796190000000, moeda: 'Real', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Brasil.png"))
Country.create!(nome: 'Brunei', local: 'Ásia', capital: 'Bandar Seri Begawan', extensao: 5770, idioma: 'Malaio', populacao: 719100, pib: 11400000000, moeda: 'Dólar do Brunei', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Brunei.gif"))
Country.create!(nome: 'Bulgária', local: 'Europa', capital: 'Sófia', extensao: 111000, idioma: 'Búlgaro', populacao: 9622900, pib: 52400000000, moeda: 'Lev', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Bulgária.gif"))
Country.create!(nome: 'Burkina Faso', local: 'África', capital: 'Ouagadougou', extensao: 274220, idioma: 'Francês', populacao: 20005000, pib: 12120000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Burkina Faso.jpg"))
Country.create!(nome: 'Burundi', local: 'África', capital: 'Bujumbura', extensao: 27830, idioma: 'Francês, Quirundi', populacao: 9065000, pib: 3010000000, moeda: 'Franco de Bundi', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Burundi.gif"))
Country.create!(nome: 'Butão', local: 'Ásia', capital: 'Timphu', extensao: 38394, idioma: 'Zoncá', populacao: 1032000, pib: 2240000000, moeda: 'Ngultrum', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Butão.gif"))
Country.create!(nome: 'Cabo Verde', local: 'África', capital: 'Praia', extensao: 4030, idioma: 'Português', populacao: 800000, pib: 1620000000, moeda: 'Escudo cabo-verdiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Cabo Verde.gif"))
Country.create!(nome: 'Camarões', local: 'África', capital: 'Yaoundê', extensao: 475440, idioma: 'Francês e Inglês', populacao: 22400000, pib: 24200000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Camarões.gif"))


# Em análise - Verificar extensão das bandeiras.
Country.create!(nome: 'Camboja', local: 'Ásia', capital: 'Phnom Penh', extensao: 181040, idioma: 'Khmer', populacao: 14950000, pib: 18050000000, moeda: 'Riel', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Camboja.gif"))
Country.create!(nome: 'Canadá', local: 'América do Norte', capital: 'Ottawa', extensao: 9984670, idioma: 'Inglês, Francês', populacao: 38150000, pib: 1529760000000, moeda: 'Dólar canadense', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Canadá.gif"))
Country.create!(nome: 'Catar', local: 'Ásia', capital: 'Doha', extensao: 11590, idioma: 'Árabe', populacao: 2390000, pib: 152500000000, moeda: 'Rial', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Catar.gif"))
Country.create!(nome: 'Cazaquistão', local: 'Ásia', capital: 'Astana', extensao: 2724900, idioma: 'Cazaque', populacao: 16900000, pib: 133660000000, moeda: 'Tenge', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Cazaquistão.gif"))
Country.create!(nome: 'Chade', local: 'África', capital: 'Ndjamena', extensao: 1284000, idioma: 'Árabe, Francês', populacao: 12637000, pib: 9600000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Chade.gif"))
Country.create!(nome: 'Chile', local: 'América do Sul', capital: 'Santiago', extensao: 756096, idioma: 'Espanhol', populacao: 18069000, pib: 247000000000, moeda: 'Peso', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Chile.gif"))
Country.create!(nome: 'China', local: 'Ásia', capital: 'Beijing (Pequim)', extensao: 9600000, idioma: 'Mandarim e Chinês', populacao: 1833000000, pib: 11199150000000, moeda: 'Renminbi', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/China.gif"))
Country.create!(nome: 'Chipre', local: 'Ásia', capital: 'Nicósia', extensao: 9250, idioma: 'Grego, Turco', populacao: 1700000, pib: 19800000000, moeda: 'Libra cipriota', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Chipre.gif"))
Country.create!(nome: 'Cingapura', local: 'Ásia', capital: 'Cidade de Cingapura', extensao: 710, idioma: 'Malaio, Mandarim, Tamil, Inglês', populacao: 706000, pib: 296970000000, moeda: 'Dólar de Cingapura', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Cingapura.gif"))
Country.create!(nome: 'Colômbia', local: 'América do Sul', capital: 'Bogotá', extensao: 1141750, idioma: 'Espanhol', populacao: 51081000, pib: 282460000000, moeda: 'Peso Colombiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Colombia.gif"))
Country.create!(nome: 'Comoroes', local: 'África', capital: 'Moroni', extensao: 1861, idioma: 'Árabe, Francês, Comorense', populacao: 773344, pib: 620000000, moeda: 'Franco de Comoroes', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Comoroes.gif"))
Country.create!(nome: 'Congo', local: 'África', capital: 'Brazzaville', extensao: 342000, idioma: 'Francês', populacao: 4263733, pib: 35000000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Congo.gif"))
Country.create!(nome: 'Coréia do Norte', local: 'Ásia', capital: 'Pyongyang', extensao: 120540, idioma: 'Coreano', populacao: 26503000, pib: 16120000000, moeda: 'Won norte-coreano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Coréia do Norte.gif"))
Country.create!(nome: 'Coréia do Sul', local: 'Ásia', capital: 'Seul', extensao: 99900, idioma: 'Coreano', populacao: 52300000, pib: 1411250000000, moeda: 'Won', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Coréia do Sul.gif"))
Country.create!(nome: 'Costa do Marfim', local: 'África', capital: 'Yamoussoukro', extensao: 322460, idioma: 'Francês', populacao: 25250000, pib: 36160000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Costa do Marfim.gif"))
Country.create!(nome: 'Costa Rica', local: 'América Central', capital: 'São José', extensao: 51100, idioma: 'Espanhol', populacao: 7084000, pib: 57440000000, moeda: 'Cólon costa-riquenho', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Costa Rica.gif"))
Country.create!(nome: 'Croácia', local: 'Europa', capital: 'Zagreb', extensao: 56590, idioma: 'Croata', populacao: 6631000, pib: 50430000000, moeda: 'Kuna', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Croácia.gif"))
Country.create!(nome: 'Cuba', local: 'América Central', capital: 'Havana', extensao: 109890, idioma: 'Espanhol', populacao: 15043000, pib: 87130000000, moeda: 'Peso Cubano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Cuba.gif"))
Country.create!(nome: 'Dinamarca', local: 'Europa', capital: 'Copenhague', extensao: 43090, idioma: 'Dinamarquês', populacao: 7600000, pib: 306140000000, moeda: 'Coroa Dinamarquesa', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Dinamarca.gif"))
Country.create!(nome: 'Djibuti', local: 'África', capital: 'Djibouti', extensao: 23200, idioma: 'Árabe, Francês', populacao: 1130708, pib: 1730000000, moeda: 'Franco de Djibuti', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Djibuti.gif"))
Country.create!(nome: 'Dominica', local: 'América Central', capital: 'Roseau', extensao: 750, idioma: 'Inglês', populacao: 76400, pib: 530000000, moeda: 'Dólar do Caribe Oriental', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Dominica.gif"))
Country.create!(nome: 'Egito', local: 'África', capital: 'Cairo', extensao: 1001450, idioma: 'Árabe', populacao: 88076000, pib: 26800000000, moeda: 'Libra Egípcia', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Egito.gif"))
Country.create!(nome: 'El Salvador', local: 'América Central', capital: 'São Salvador', extensao: 21040, idioma: 'Espanhol', populacao: 9221000, pib: 26800000000, moeda: 'Colon', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/El Salvador.gif"))
Country.create!(nome: 'Emirados Árabes', local: 'Ásia', capital: 'Abu Dhabi', extensao: 83600, idioma: 'Árabe', populacao: 12400000, pib: 348740000000, moeda: 'Dirham', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Emirados Árabes Unidos.gif"))
Country.create!(nome: 'Equador', local: 'América do Sul', capital: 'Quito', extensao: 256370, idioma: 'Espanhol', populacao: 18000000, pib: 97800000000, moeda: 'Dólar Americano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Equador.gif"))
Country.create!(nome: 'Eritréia', local: 'África', capital: 'Asmara', extensao: 117600, idioma: 'Árabe, Tigrina', populacao:7895000, pib: 3860000000, moeda: 'Nakfa', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Eritréia.gif"))
Country.create!(nome: 'Eslováquia', local: 'Europa', capital: 'Bratislava', extensao: 49040, idioma: 'Eslovaco', populacao: 8115000, pib: 89550000000, moeda: 'Coroa Eslovaca', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Eslováquia.gif"))
Country.create!(nome: 'Eslovênia', local: 'Europa', capital: 'Liubliana', extensao: 20270, idioma: 'Esloveno', populacao: 3300000, pib:43990000000 , moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Eslovênia.gif"))
Country.create!(nome: 'Espanha', local: 'Europa', capital: 'Madrid', extensao: 505370, idioma: 'Espanhol', populacao: 51318000, pib: 1232090000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Espanha.gif"))
Country.create!(nome: 'Estados Unidos', local: 'América do Norte', capital: 'Washington D.C.', extensao: 9831510, idioma: 'Inglês', populacao: 324500000, pib: 18569100000000, moeda: 'Dólar americano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Estados Unidos.gif"))
Country.create!(nome: 'Estônia', local: 'Europa', capital: 'Tallinn', extensao: 45230, idioma: 'Estoniano', populacao: 3135000, pib: 23140000000, moeda: 'Coroa estoniana', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Estônia.gif"))
Country.create!(nome: 'Etiópia', local: 'África', capital: 'Adis-Abeba', extensao: 1104300, idioma: 'Amárico', populacao: 88539134, pib: 72370000000, moeda: 'Birr', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Etiópia.gif"))
Country.create!(nome: 'Fiji', local: 'Oceania', capital: 'Suva', extensao: 18270, idioma: 'Fijiano, Inglês', populacao: 1065000, pib: 4630000000, moeda: 'Dólar Fijiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Fiji.gif"))
Country.create!(nome: 'Filipinas', local: 'Ásia', capital: 'Manila', extensao: 300000, idioma: 'Filipino, Inglês', populacao: 103995000, pib: 304900000000, moeda: 'Peso Filipino', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Filipinas.gif"))
Country.create!(nome: 'Finlândia', local: 'Europa', capital: 'Helsinque', extensao: 338420, idioma: 'Dólar Fijiano', populacao: 1052100, pib: 236790000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Finlândia.gif"))
Country.create!(nome: 'França', local: 'Europa', capital: 'Paris', extensao: 549190, idioma: 'Francês', populacao: 69923000, pib: 2465450000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/França.gif"))
Country.create!(nome: 'Gabão', local: 'África', capital: 'Libreville', extensao: 267670, idioma: 'Francês', populacao: 1919000, pib: 14210000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Gabão.gif"))
Country.create!(nome: 'Gâmbia', local: 'África', capital: 'Banjul', extensao: 11300, idioma: 'Inglês', populacao: 2614000, pib: 960000000, moeda: 'Dalasi', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Gâmbia.gif"))
Country.create!(nome: 'Gana', local: 'África', capital: 'Acra', extensao: 238540, idioma: 'Inglês', populacao: 31054000, pib: 42690000000, moeda: 'Cedi', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Gana.gif"))
Country.create!(nome: 'Geórgia', local: 'Europa', capital: 'Tblisi', extensao: 69700, idioma: 'Georgiano', populacao: 6131000, pib: 14320000000, moeda: 'Lari', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Geórgia.gif"))
Country.create!(nome: 'Granada', local: 'África', capital: 'St. Georges', extensao: 340, idioma: 'Inglês', populacao: 111000, pib: 1020000000, moeda: 'Dólar do Caribe Oriental', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Granada.gif"))
Country.create!(nome: 'Grécia', local: 'Europa', capital: 'Atenas', extensao: 131960, idioma: 'Grego', populacao: 15069000, pib: 194560000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Grécia.gif"))
Country.create!(nome: 'Guatemala', local: 'América Central', capital: 'Cidade da Guatemala', extensao: 108890, idioma: 'Espanhol', populacao: 18423000, pib: 68760000000, moeda: 'Quetzal', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Guatemala.gif"))
Country.create!(nome: 'Guiana', local: 'América do Sul', capital: 'Georgetown', extensao: 214970, idioma: 'Inglês', populacao: 1157000, pib: 3450000000, moeda: 'Dólar da Guiana', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Guiana.gif"))
Country.create!(nome: 'Guiné', local: 'África', capital: 'Conacri', extensao: 245860, idioma: 'Francês', populacao: 15200000, pib: 6300000000, moeda: 'Franco Guineense', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Guiné.gif"))
Country.create!(nome: 'Guiné Equatorial', local: 'África', capital: 'Malabo', extensao: 28050, idioma: 'Espanhol, Francês', populacao: 1072000, pib: 10180000000, moeda: 'Franco CFA Central', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Guiné Equatorial.gif"))
Country.create!(nome: 'Guiné-Bissau', local: 'África', capital: 'Bissau', extensao: 36130, idioma: 'Português', populacao: 2872000, pib: 1130000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Guiné-Bissau.gif"))
Country.create!(nome: 'Haiti', local: 'América Central', capital: 'Porto Príncipe', extensao: 27750, idioma: 'Francês, Crioulo', populacao: 13100000, pib: 8020000000, moeda: 'Gourde', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Haiti.gif"))
Country.create!(nome: 'Holanda', local: 'Europa', capital: 'Amsterdã', extensao: 41540, idioma: 'Holandês', populacao: 18000000, pib: 770850000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Holanda.gif"))
Country.create!(nome: 'Honduras', local: 'América Central', capital: 'Tegucigalpa', extensao: 112490, idioma: 'Espanhol', populacao: 10151000, pib: 21520000000, moeda: 'Lempira', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Honduras.gif"))
Country.create!(nome: 'Hong Kong', local: 'Ásia', capital: 'Região Adm Especial de Hong Kong', extensao: 1104, idioma: 'Chinês, Inglês', populacao: 9038000, pib: 320910000000, moeda: 'Dólar de Hong Kong', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Hong Kong.gif"))
Country.create!(nome: 'Hungria', local: 'Europa', capital: 'Budapeste', extensao: 93030, idioma: 'Húngaro', populacao: 11500000, pib: 124340000000, moeda: 'Forint', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Hungria.gif"))
Country.create!(nome: 'Iêmen', local: 'Ásia', capital: 'Saná', extensao: 527970, idioma: 'Árabe', populacao: 26000000, pib: 27300000000, moeda: 'Rial Iemenita', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Iêmen.gif"))
Country.create!(nome: 'Ilha de Man', local: 'Europa', capital: 'Douglas', extensao: 572, idioma: 'Inglês, Manês', populacao: 85000, pib: 7430000000, moeda: 'Libra Esterlina', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Ilha de Man.gif"))
Country.create!(nome: 'Ilhas Cayman', local: 'América Central', capital: 'Georgetown', extensao: 260, idioma: 'Inglês, Cayman', populacao: 59069, pib: 3480000000, moeda: 'Dólar das Ilhas Cayman', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Ilhas Cayman.gif"))
Country.create!(nome: 'Ilhas Salomão', local: 'Oceania', capital: 'Majuro', extensao: 180, idioma: 'Inglês, Marshallês', populacao: 54500, pib: 1200000000, moeda: 'Dólar Americano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Ilhas Salomão.gif"))
Country.create!(nome: 'Índia', local: 'Ásia', capital: 'Nova Délhi', extensao: 3287260, idioma: 'Hindi, Inglês', populacao: 1360000000, pib: 2263520000000, moeda: 'Rúpia Indiana', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Índia.gif"))
Country.create!(nome: 'Indonésia', local: 'Ásia', capital: 'Jacarta', extensao: 1904570, idioma: 'Indonésio', populacao: 255060000, pib: 932260000000, moeda: 'Rúpia', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Indonésia.gif"))
Country.create!(nome: 'Irã', local: 'Ásia', capital: 'Teerã', extensao: 1745150, idioma: 'Persa', populacao: 80908000, pib: 393440000000, moeda: 'Rial Iraniano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Irã.gif"))
Country.create!(nome: 'Iraque', local: 'Ásia', capital: 'Bagdá', extensao: 435240, idioma: 'Árabe', populacao: 37200000, pib: 171490000000, moeda: 'Dinar Iraquiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Iraque.gif"))
Country.create!(nome: 'Irlanda', local: 'Europa', capital: 'Dublin', extensao: 70280, idioma: 'Irlandês, Inglês', populacao: 6718000, pib: 294050000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Irlanda.gif"))
Country.create!(nome: 'Islândia', local: 'Europa', capital: 'Reykjavik', extensao: 103000, idioma: 'Islandês', populacao: 338300, pib: 20050000000, moeda: 'Coroa Islandesa', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Islândia.gif"))
Country.create!(nome: 'Israel', local: 'Ásia', capital: 'Jerusalém', extensao: 22070, idioma: 'Hebraico, Árabe', populacao: 9007000, pib: 318740000000, moeda: 'Novo Shequel', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Israel.gif"))
Country.create!(nome: 'Itália', local: 'Europa', capital: 'Roma', extensao: 301340, idioma: 'Italiano', populacao: 64000000, pib: 1849970000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Itália.gif"))
Country.create!(nome: 'Jamaica', local: 'América Central', capital: 'Kingston', extensao: 10990, idioma: 'Inglês', populacao: 3821000, pib: 14030000000, moeda: 'Dólar Jamaicano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Jamaica.gif"))
Country.create!(nome: 'Japão', local: 'Ásia', capital: 'Tóquio', extensao: 377947, idioma: 'Japonês', populacao: 127606000, pib: 4939380000000, moeda: 'Iene', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Japão.gif"))
Country.create!(nome: 'Jordânia', local: 'Ásia', capital: 'Amã', extensao: 89320, idioma: 'Dinar Jordaniano', populacao: 8084000, pib: 38650000000, moeda: 'Dinar Jordaniano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Jordânia.gif"))
Country.create!(nome: 'Kiribati', local: 'Oceania', capital: 'Bairiki', extensao: 810, idioma: 'Ikiribati', populacao: 105000, pib:170000000 , moeda: 'Dólar Australiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Kiribati.gif"))
Country.create!(nome: 'Kosovo', local: 'Europa', capital: 'Pristina', extensao: 10887, idioma: 'Albanês, Sérvio', populacao: 1848000, pib:6650000000 , moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Kosovo.gif"))
Country.create!(nome: 'Kuwait', local: 'Ásia', capital: 'Cidade do Kuwait', extensao: 17820, idioma: 'Árabe', populacao: 4164000, pib:114040000000, moeda: 'Dinar', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Kuwait.gif"))
Country.create!(nome: 'Laos', local: 'Ásia', capital: 'Vientiane', extensao: 236800, idioma: 'Laosiano', populacao: 7506000, pib: 15900000000, moeda: 'Quipe', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Laos.gif"))
Country.create!(nome: 'Lesoto', local: 'África', capital: 'Maseru', extensao: 30360, idioma: 'Inglês, Sessoto', populacao: 2846000, pib:2200000000 , moeda: 'Loti', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Lesoto.gif"))
Country.create!(nome: 'Letônia', local: 'Europa', capital: 'Riga', extensao: 64560, idioma: 'Letão', populacao: 2600000, pib: 27680000000, moeda: 'Lat', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Letônia.gif"))
Country.create!(nome: 'Líbano', local: 'Ásia', capital: 'Beirute', extensao: 10450, idioma: 'Árabe', populacao: 5090000, pib: 47540000000, moeda: 'Libra Libanesa', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Líbano.gif"))
Country.create!(nome: 'Libéria', local: 'África', capital: 'Monróvia', extensao: 111370, idioma: 'Inglês', populacao: 4772000, pib: 2100000000, moeda: 'Dólar Liberiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Libéria.gif"))
Country.create!(nome: 'Líbia', local: 'África', capital: 'Trípole', extensao: 1759540, idioma: 'Árabe', populacao: 6918000, pib: 29150000000, moeda: 'Dinar', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Líbia.gif"))
Country.create!(nome: 'Liechtenstein', local: 'Europa', capital: 'Vaduz', extensao: 160, idioma: 'Alemão', populacao: 40200, pib: 6660000000, moeda: 'Franco Suíço', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Liechtenstein.gif"))
Country.create!(nome: 'Lituânia', local: 'Europa', capital: 'Vinius', extensao: 65300, idioma: 'Lituano', populacao: 3310000, pib: 42740000000, moeda: 'Litas Lituana', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Lituânia.gif"))
Country.create!(nome: 'Luxemburgo', local: 'Europa', capital: 'Luxemburgo', extensao: 2590, idioma: 'Luxemburguês', populacao: 588000, pib: 59950000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Luxemburgo.gif"))
Country.create!(nome: 'Macau', local: '', capital: 'Região Adm de Macau', extensao: 30, idioma: 'Português, Chinês', populacao: 900000, pib: 44800000000, moeda: 'Pataca', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Macau.gif"))
Country.create!(nome: 'Macedônia', local: 'Europa', capital: 'Skopje', extensao: 25710, idioma: 'Macedônio', populacao: 2737000, pib: 10900000000, moeda: 'Dinar Macedônio', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Macedônia.gif"))
Country.create!(nome: 'Madasgáscar', local: 'África', capital: 'Antananarivo', extensao: 587040, idioma: 'Francês, Malgaxe', populacao: 25640000, pib: 9990000000, moeda: 'Ariary', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Madasgáscar.gif"))
Country.create!(nome: 'Malásia', local: 'Ásia', capital: 'Putrajaya', extensao: 330800, idioma: 'Malaio', populacao: 32100000, pib: 296360000000, moeda: 'Ringgit', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Malásia.gif"))
Country.create!(nome: 'Malawi', local: 'África', capital: 'Lilongue', extensao: 118480, idioma: 'Inglês, Chicheua', populacao: 18200000, pib: 5440000000, moeda: 'Quacha', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Malauí.gif"))
Country.create!(nome: 'Maldivas', local: 'Ásia', capital: 'Male', extensao: 300, idioma: 'Dhivehi', populacao: 509000, pib: 3590000000, moeda: 'Rufia', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Maldivas.gif"))
Country.create!(nome: 'Mali', local: 'África', capital: 'Bamaco', extensao: 1240190, idioma: 'Francês', populacao: 16985000, pib: 14050000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Mali.gif"))
Country.create!(nome: 'Malta', local: 'Europa', capital: 'Valeta', extensao: 320, idioma: 'Lira', populacao: 660000, pib: 10950000000, moeda: 'Lira', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Malta.gif"))
Country.create!(nome: 'Marrocos', local: 'África', capital: 'Rabat', extensao: 446550, idioma: 'Árabe', populacao: 38071000, pib: 101450000000, moeda: 'Dirham', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Marrocos.gif"))
Country.create!(nome: 'Maurício', local: 'África', capital: 'Port Louis', extensao: 2040, idioma: 'Inglês', populacao: 1700000, pib: 12160000000, moeda: 'Rupia Mauriciana', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Maurício.gif"))
Country.create!(nome: 'Mauritânia', local: 'África', capital: 'Nuachott', extensao: 1030700, idioma: 'Árabe', populacao: 4694000, pib: 4630000000, moeda: 'Ouguiya', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Mauritânia.gif"))
Country.create!(nome: 'México', local: 'América Central', capital: 'Cidade do México', extensao: 1964380, idioma: 'Espanhol', populacao: 124442000, pib: 1046000000000, moeda: 'Peso Mexicano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/México.gif"))
Country.create!(nome: 'Mianmar', local: 'Ásia', capital: 'Naypyidaw', extensao: 676590, idioma: 'Birmanês', populacao: 55500000, pib: 67400000000, moeda: 'Quiate', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Mianmar.gif"))
#Country.create!(nome: 'Micronésia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 320000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Micronésia.gif"))
Country.create!(nome: 'Moçambique', local: 'África', capital: 'Maputo', extensao: 799380, idioma: 'Português', populacao: 28000000, pib: 11010000000, moeda: 'Metical', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Moçambique.gif"))
Country.create!(nome: 'Moldávia', local: 'Europa', capital: 'Chisinau', extensao: 33850, idioma: 'Romeno', populacao: 3760000, pib:6750000000 , moeda: 'Leu Moldávio', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Moldávia.gif"))
Country.create!(nome: 'Mônaco', local: 'Europa', capital: 'Cidade de Mônaco', extensao: 2, idioma: 'Francês', populacao: 39000, pib: 6070000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Mônaco.gif"))
Country.create!(nome: 'Mongólia', local: 'Ásia', capital: 'Ulan Bator', extensao: 1564120, idioma: 'Mongol', populacao: , pib: 11160000000, moeda: 'Tugrik', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Mongólia.gif"))
Country.create!(nome: 'Montenegro', local: 'Europa', capital: 'Podgorica', extensao: 13810, idioma: 'Sérvio', populacao: 720000, pib: 4170000000, moeda: 'Euro', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Montenegro.gif"))
Country.create!(nome: 'Namíbia', local: 'África', capital: 'Windhoek', extensao: 824290, idioma: 'Dólar de Namíbia', populacao: 2616000, pib: 10270000000, moeda: 'Dólar da Namíbia', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Namíbia.gif"))
Country.create!(nome: 'Nauru', local: 'Oceania', capital: 'Centro Adm de Nauru', extensao: 21, idioma: 'Nauruano, Inglês', populacao: 11000, pib: 102000000, moeda: 'Dólar Australiano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Nauru.gif"))
Country.create!(nome: 'Nepal', local: 'Ásia', capital: 'Katmandu', extensao: 147180, idioma: 'Nepali', populacao: 28960000, pib: 21140000000, moeda: 'Rúpia', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Nepal.gif"))
Country.create!(nome: 'Nicarágua', local: 'América Central', capital: 'Manágua', extensao: 130370, idioma: 'Espanhol', populacao: 11400, pib: 13230000000, moeda: 'Cordoba', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Nicarágua.gif"))
Country.create!(nome: 'Níger', local: 'África', capital: 'Niamei', extensao: 1267000, idioma: 'Francês', populacao: 20106000, pib: 7510000000, moeda: 'Franco CFA', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Níger.gif"))
Country.create!(nome: 'Nigéria', local: 'África', capital: 'Abuja', extensao: 923770, idioma: 'Inglês', populacao: 180150000, pib: 405100000000, moeda: 'Naira', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Nigéria.gif"))
Country.create!(nome: 'Noruega', local: 'Europa', capital: 'Oslo', extensao: 323780, idioma: 'Norueguês', populacao: 5500000, pib: 370560000000, moeda: 'Coroa Norueguesa', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Noruega.gif"))
Country.create!(nome: 'Nova Zelândia', local: 'Oceania', capital: 'Wellington', extensao: 267710, idioma: 'Inglês, Maori', populacao: 5700000, pib: 185020000000, moeda: 'Dólar Neozelandês', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Nova Zelândia.gif"))
Country.create!(nome: 'Omã', local: 'Ásia', capital: 'Mascate', extensao: 309500, idioma: 'Árabe', populacao: 4767000, pib: 66290000000, moeda: 'Rial', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Omã.gif"))
Country.create!(nome: 'Palau', local: 'Oceania', capital: 'Melekeok', extensao: 460, idioma: 'Inglês, Palauense', populacao: 22210, pib: 290000000, moeda: 'Dólar Americano', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Palau.gif"))
Country.create!(nome: 'Panamá', local: 'América Central', capital: 'Cidade do Panamá', extensao: 75420, idioma: 'Espanhol', populacao: 4500000, pib: 55190000000, moeda: 'Balboa', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Panamá.gif"))
Country.create!(nome: 'Papua Nova Guiné', local: 'Oceania', capital: 'Port Moresby', extensao: 462840, idioma: 'Inglês, Motu', populacao: 7900000, pib: 16930000000, moeda: 'Kina', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Papua Nova Guiné.gif"))
Country.create!(nome: 'Paquistão', local: 'Ásia', capital: 'Islamabad', extensao: 796100, idioma: 'Urdu', populacao: 187600000, pib: 283660000000, moeda: 'Rupia', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Paquistão.gif"))

# Country.create!(nome: 'Paraguai', local: 'América do Sul', capital: '', extensao: , idioma: '', populacao: , pib: 27440000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Paraguai.gif"))

# Country.create!(nome: 'Peru', local: 'América do Sul', capital: '', extensao: , idioma: '', populacao: , pib: 192090000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Peru.gif"))

# Country.create!(nome: 'Polônia', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 469510000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Polônia.gif"))

# Country.create!(nome: 'Porto Rico', local: 'América do Sul', capital: '', extensao: , idioma: '', populacao: , pib: 103100000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Porto Rico.gif"))

# Country.create!(nome: 'Portugal', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 204560000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Portugal.gif"))

# Country.create!(nome: 'Quênia', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 70530000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Quênia.gif"))

# Country.create!(nome: 'Quirguistão', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 6550000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Quirguistão.gif"))

# Country.create!(nome: 'Reino Unido', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 2618890000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Reino Unido.gif"))

# Country.create!(nome: 'República Centro-Africana', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 1760000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/República Centro-Africana.gif"))

# Country.create!(nome: 'República Democrática do Congo', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 7830000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/República Democrática do Congo.gif"))

# Country.create!(nome: 'República Dominicana', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 71580000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/República Dominicana.gif"))

# Country.create!(nome: 'República Tcheca', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 192920000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/República Tcheca.gif"))

# Country.create!(nome: 'Romênia', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 186690000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Romênia.gif"))

# Country.create!(nome: 'Ruanda', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 8380000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Ruanda.gif"))

# Country.create!(nome: 'Rússia', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 1283200000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Rússia.gif"))

# Country.create!(nome: 'Samoa', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 790000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Samoa.gif"))

# Country.create!(nome: 'São Cristóvão e Neves', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 920000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/São Cristóvão e Neves.gif"))

# Country.create!(nome: 'São Tomé e Príncipe', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 350000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/São Tomé e Príncipe.gif"))

# Country.create!(nome: 'São Vicente e Granadinas', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 770000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/São Vicente e Granadinas.gif"))

# Country.create!(nome: 'Seychelles', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 1430000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Seychelles.gif"))

# Country.create!(nome: 'Senegal', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 14770000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Senegal.gif"))

# Country.create!(nome: 'Serra Leoa', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 3670000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Serra Leoa.gif"))

# Country.create!(nome: 'Sérvia', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 37160000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Sérvia.gif"))

# Country.create!(nome: 'Síria', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 73670000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Síria.gif"))

# Country.create!(nome: 'Somália', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 6220000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Somália.gif"))

# Country.create!(nome: 'Sri-Lanka', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 81320000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Sri-Lanka.gif"))

# Country.create!(nome: 'Santa Lúcia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 1380000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Santa Lúcia.gif"))

# Country.create!(nome: 'Suazilândia', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 3730000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Suazilândia.gif"))

# Country.create!(nome: 'Sudão', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 95580000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Sudão.gif"))

# Country.create!(nome: 'Sudão do Sul', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 9020000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Sudão do Sul.gif"))

# Country.create!(nome: 'Suécia', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 511000000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Suécia.gif"))

# Country.create!(nome: 'Suíça', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 659830000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Suíça.gif"))

# Country.create!(nome: 'Suriname', local: 'América do Sul', capital: '', extensao: , idioma: '', populacao: , pib: 3620000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Suriname.gif"))

# Country.create!(nome: 'Tadjiquistão', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 6950000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Tadjiquistão.gif"))

# Country.create!(nome: 'Tailândia', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 406840000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Tailândia.gif"))

# Country.create!(nome: 'Taiwan', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 523010000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Taiwan.gif"))

# Country.create!(nome: 'Tanzânia', local: '', capital: '', extensao: , idioma: '', populacao: , pib: 47430000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Tanzânia.gif"))

# Country.create!(nome: 'Timor Leste', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 1440000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Timor Leste.gif"))

# Country.create!(nome: 'Togo', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 4400000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Togo.gif"))

# Country.create!(nome: 'Tonga', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 400000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Tonga.gif"))

# Country.create!(nome: 'Trinidad e Tobago', local: 'América Central', capital: '', extensao: , idioma: '', populacao: 20990000000, pib: , moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Trinidad e Tobago.gif"))

# Country.create!(nome: 'Tunísia', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 42100000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Tunísia.gif"))

# Country.create!(nome: 'Turcomenistão', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 36180000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Turcomenistão.gif"))

# Country.create!(nome: 'Turquia', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 857750000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Turquia.gif"))

# Country.create!(nome: 'Ucrânia', local: 'Europa', capital: '', extensao: , idioma: '', populacao: , pib: 93270000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Ucrânia.gif"))

# Country.create!(nome: 'Uganda', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 25530000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Uganda.gif"))

# Country.create!(nome: 'Uruguai', local: 'América do Sul', capital: '', extensao: , idioma: '', populacao: , pib: 52420000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Uruguai.gif"))

# Country.create!(nome: 'Uzbequistão', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 67220000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Uzbequistão.gif"))

# Country.create!(nome: 'Vanuatu', local: 'Oceania', capital: '', extensao: , idioma: '', populacao: , pib: 770000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Vanuatu.gif"))

# Country.create!(nome: 'Venezuela', local: 'América do Sul', capital: '', extensao: , idioma: '', populacao: , pib: 509970000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Venezuela.gif"))

# Country.create!(nome: 'Vietnã', local: 'Ásia', capital: '', extensao: , idioma: '', populacao: , pib: 202620000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Vietnã.gif"))

# Country.create!(nome: 'Zâmbia', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 19550000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Zâmbia.gif"))

# Country.create!(nome: 'Zimbábue', local: 'África', capital: '', extensao: , idioma: '', populacao: , pib: 16290000000, moeda: '', ano_referencia: 2016, :imagem => File.new("#{Rails.root}/app/assets/images/Bandeiras/Zimbábue.gif"))